### ISSUE TITLE
downscale DTR using tasmax and tasmin 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#176]
As we've discussed, we'll be running tasmax and diurnal temperature range (DTR, e.g. tasmax - tasmin), along with daily precip through our pipeline. DTR will be treated as a `multiplicative` type of variable (like precip) as opposed to additive. 

This means that we need to add two steps to our pipeline: 
1) make sure that DTR is being computed at the beginning after cleaning tasmax and tasmin (this might already exist?)
2) after downscaling, we'll need a step to compute tasmin from tasmax and DTR, which is what we'll be using/sharing

**Comment by brews** [comment]
We've had DTR in the past but, not with the scheme described here, as we ran tasmin just like any other variable rather than derived from existing downscaled output.

So, it sounds like we need a `dtr` parameter file that specs both tasmin and tasmax inputs in the `historical` and `ssps` lists.

The parameter file for tasmin would then indicate the `dtr` and `tasmax` downscaling output zarr stores to use as input.

**Comment by dgergel** [comment]
If we had that `dtr` parameter file with both tasmin and tasmax specs, would we be cleaning tasmax twice? 

Interesting - that would work for tasmin but that's not how I was thinking about it. I was thinking we would have DTR and tasmax parameter files, and the DTR would ultimately produce tasmin.

**Comment by brews** [comment]
Closed with PR #335
