### ISSUE TITLE
Detailed description of QPLAD

### ISSUE THREAD

**Issue by david0811** [ClimateImpactLab/downscaleCMIP6#632]
Hello! Thank you for providing this great resource for the community. Is there a detailed description anywhere of the QPLAD methodology? I am specifically wondering about how it handles the spatial structure of downscaled fields and to what extent it differs from the LOCA method of [Pierce et al. (2014)](http://journals.ametsoc.org/doi/abs/10.1175/JHM-D-14-0082.1). Thanks!

**Comment by delgadom** [comment]
Hi there! thanks for your interest in the dataset and method! We’re currently working on submitting a paper which will go into much greater detail about the method and findings, and we’ll post the preprint as soon as it’s available.

I can briefly summarize the method: the QPLAD method uses a single quantile from the coarse bias corrected GCM, and uses it to select a single day from the fine-resolution reference dataset, such that the quantile of the coarsened reference dataset matches that of the GCM. In this way, the observed day for all fine-resolution pixels within the given coarse-resolution grid cell are taken as a single “analog”. The within-cell deviations from the coarse-resolution means are then used to downscale the coarse-resolution bias corrected GCM.

Without being too familiar with Pierce et al. (2014), I can say that one difference which immediately jumps out is that we did not interpolate the quantiles across space. Therefore, our downscaled data will have edge effects, as the fine-resolution pixels from neighboring coarse grid cells will have within-cell deviations taken from different days. However, because these are within-pixel deviations taken from actual historical observations, edge pixels will reflect the full CDF from observations.

**Comment by kemccusker** [comment]
Hi there @david0811, I wanted to make sure you saw that our paper is up as a [preprint](https://egusphere.copernicus.org/preprints/2023/egusphere-2022-1513/). Hope it's helpful!

**Comment by delgadom** [comment]
closing this as the pre-print publication (linked above) has a more detailed description. Please feel free to raise another issue if you have additional questions!
